-- phpMyAdmin SQL Dump
-- version 4.5.5.1
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: 2019-01-17 05:25:20
-- 服务器版本： 5.7.11
-- PHP Version: 5.6.19

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

--
-- 表的结构 `zy_zyconfig`
--
CREATE TABLE IF NOT EXISTS `zy_zyconfig` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `config_name` varchar(255) NOT NULL COMMENT '配置名称',
  `model_name` varchar(255) NOT NULL COMMENT '所需模块',
  `item_name` varchar(255) NOT NULL COMMENT '模块项目名',
  `url` varchar(255) NOT NULL COMMENT '地址',
  `api_url` varchar(255) NOT NULL COMMENT 'API地址',
  `explain` text NOT NULL COMMENT '说明',
  `api_explain` text NOT NULL COMMENT 'api说明',
  `key` VARCHAR(255) NOT NULL COMMENT '配置表的关键字',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

DELETE FROM zy_zyconfig WHERE `item_name`='zyaddr';
INSERT INTO `zy_zyconfig` (`config_name`, `model_name`, `item_name`, `url`, `api_url`, `explain`, `api_explain`, `key`) VALUES
('删除地址', 'zyaddr 地址管理', 'zyaddr', 'localhost/zm/index.php?m=zyaddr&c=zyaddr_api&a=del', '域名/index.php?m=zyaddr&c=zyaddr_api&a=del', '一、应用模块：地址模块      配置来源：删除会员地址信息\r\n\r\n二、用途：用于用户地址\r\n\r\n三、提供参数：\r\n\r\n 1）请求参数说明：\r\n      id（ID)\r\n\r\n 2）返回格式： json\r\n\r\n 3）请求方式： http  get', '一、请求参数：\r\n\r\n 1）请求参数说明：\r\n\r\n      id （id）\r\n\r\n 2）请求方式： http get\r\n\r\n\r\n二、返回信息 :\r\n\r\n  返回格式：{ "status": "success", "code": 200, "message": "操作成功" }\r\n\r\n\r\n三、返回字段解释：\r\n\r\n\r\n  status: 操作成功/操作失败\r\n\r\n  code: 操作状态\r\n\r\n  message: 提示信息\r\n\r\n四、状态信息说明：\r\n\r\n 200：操作成功\r\n\r\n 10001： ID为空\r\n\r\n 10010： 删除失败\r\n\r\n\r\n五、实例代码：\r\n\r\n<script type="javascript/text">\r\n\r\n$.ajax({\r\n\r\n  url:''域名/index.php?m=zyaddr&c=zyaddr_api&a=del'',\r\n\r\n  data:{id:1},\r\n\r\n  dataType:''json'',\r\n\r\n  type:''get'',\r\n\r\n  success:function(res){\r\n\r\n  { "status": "success", "code": 200, "message": "操作成功" }\r\n\r\n  },\r\n\r\n});\r\n\r\n</script>', 'zyaddr4'),
('地址列表', 'zyaddr 地址管理', 'zyaddr', 'localhost/zm/index.php?m=zyaddr&c=zyaddr_api&a=lists', '域名/index.php?m=zyaddr&c=zyaddr_api&a=lists', '一、应用模块：地址模块      配置来源：获取会员地址信息\n\n二、用途：用于用户地址\n\n三、提供参数：\n\n 1）请求参数说明：\n      userid（会员ID)\n\n 2）返回格式： json\n\n 3）请求方式： http  get', '一、请求参数：\n\n\n\n 1）请求参数说明：\n\n      userid （用户userid）\n\n 2）请求方式： http get\n\n\n二、返回信息 :\n\n  返回格式：{ "status": "success", "code": 200, "message": "查询成功", "data": [ { "id": "3", "userid": "54", "name": "李刚", "phone": "15820657895", "province": "安徽省", "city": "合肥市", "district": "瑶海区", "address": "测试地址", "default": "1" } ] }\n\n\n三、返回字段解释：\n\n\n  status: 操作成功/操作失败\n\n  code: 操作状态\n\n  message: 提示信息\n\n  data: [ ] 数据组\n\n    data.id : ID, \n    data.userid": 会员ID, \n    data.name":  收件人, \n    data.phone": 手机号码, \n    data.province": 省, \n    data.city": 市, \n    data.district": 区, \n    data.address": 详细地址, \n    data.default": 是否默认 1默认 0 非默认\n\n四、状态信息说明：\n\n 200：操作成功\n\n 10001： 用户ID为空\n\n\n五、实例代码：\n\n<script type="javascript/text">\n\n$.ajax({\n\n  url:''域名/index.php?m=zyaddr&c=zyaddr_api&a=lists'',\n\n  data:{userid:1},\n\n  dataType:''json'',\n\n  type:''get'',\n\n  success:function(res){\n\n   { "status": "success", "code": 200, "message": "查询成功", "data": [ { "id": "3", "userid": "54", "name": "李刚", "phone": "15820657895", "province": "安徽省", "city": "合肥市", "district": "瑶海区", "address": "测试地址", "default": "1" } ] }\n\n  },\n\n});\n\n</script>', 'zyaddr1'),
('添加地址', 'zyaddr 地址管理', 'zyaddr', 'localhost/zm/index.php?m=zyaddr&c=zyaddr_api&a=add', '域名/index.php?m=zyaddr&c=zyaddr_api&a=add', '一、应用模块：地址模块      配置来源：添加会员地址信息\r\n\r\n二、用途：用于用户地址\r\n\r\n三、提供参数：\r\n\r\n 1）请求参数说明：\r\n     * @param userid 用户id\r\n     * @param name 收件人\r\n     * @param phone 手机号码\r\n     * @param province 省\r\n     * @param city 市\r\n     * @param distrct 区\r\n     * @param address 详细地址\r\n     * @param default 默认\r\n\r\n 2）返回格式： json\r\n\r\n 3）请求方式： http  get', '一、请求参数：\r\n\r\n 1）请求参数说明：\r\n     * @param userid 用户id\r\n     * @param name 收件人\r\n     * @param phone 手机号码\r\n     * @param province 省\r\n     * @param city 市\r\n     * @param distrct 区\r\n     * @param address 详细地址\r\n     * @param default 默认\r\n\r\n 2）请求方式： http get\r\n\r\n\r\n二、返回信息 :\r\n\r\n  返回格式：{ "status": "success", "code": 200, "message": "操作成功" }\r\n\r\n三、返回字段解释：\r\n\r\n  status: 操作成功/操作失败\r\n\r\n  code: 操作状态\r\n\r\n  message: 提示信息\r\n\r\n四、状态信息说明：\r\n\r\n 200：操作成功\r\n 10001： userid为空\r\n 10002： 收件人为空\r\n 10003： 手机号码为空\r\n 10004： 省为空\r\n 10005： 市为空\r\n 10006： 区为空\r\n 10007： 详细地址为空\r\n 10010： 操作失败\r\n\r\n五、实例代码：\r\n\r\n<script type="javascript/text">\r\n\r\n$.ajax({\r\n\r\n  url:''域名/index.php?m=zyaddr&c=zyaddr_api&a=del'',\r\n\r\n  data:{id:"1",\r\n     userid:"1",\r\n     name :"收件人",\r\n     phone:" 手机号码",\r\n     province :"省",\r\n     city :"市",\r\n     distrct :"区",\r\n     address :"详细地址",\r\n     default :"1",\r\n},\r\n\r\n  dataType:''json'',\r\n\r\n  type:''get'',\r\n\r\n  success:function(res){\r\n\r\n  { "status": "success", "code": 200, "message": "操作成功" }\r\n\r\n  },\r\n\r\n});\r\n\r\n</script>', 'zyaddr2'),
('编辑地址', 'zyaddr 地址管理', 'zyaddr', 'localhost/zm/index.php?m=zyaddr&c=zyaddr_api&a=edit', '域名/index.php?m=zyaddr&c=zyaddr_api&a=edit', '一、应用模块：地址模块      配置来源：编辑会员地址信息\r\n\r\n二、用途：用于用户地址\r\n\r\n三、提供参数：\r\n\r\n 1）请求参数说明：\r\n     * @param id ID\r\n     * @param userid 用户id\r\n     * @param name 收件人\r\n     * @param phone 手机号码\r\n     * @param province 省\r\n     * @param city 市\r\n     * @param distrct 区\r\n     * @param address 详细地址\r\n     * @param default 默认\r\n\r\n 2）返回格式： json\r\n\r\n 3）请求方式： http  get', '一、请求参数：\r\n\r\n 1）请求参数说明：\r\n     * @param id ID\r\n     * @param userid 用户id\r\n     * @param name 收件人\r\n     * @param phone 手机号码\r\n     * @param province 省\r\n     * @param city 市\r\n     * @param distrct 区\r\n     * @param address 详细地址\r\n     * @param default 默认\r\n\r\n 2）请求方式： http get\r\n\r\n\r\n二、返回信息 :\r\n\r\n  返回格式：{ "status": "success", "code": 200, "message": "操作成功" }\r\n\r\n三、返回字段解释：\r\n\r\n  status: 操作成功/操作失败\r\n\r\n  code: 操作状态\r\n\r\n  message: 提示信息\r\n\r\n四、状态信息说明：\r\n\r\n 200：操作成功\r\n 10001： userid为空\r\n 10002： 收件人为空\r\n 10003： 手机号码为空\r\n 10004： 省为空\r\n 10005： 市为空\r\n 10006： 区为空\r\n 10007： 详细地址为空\r\n 10010： 操作失败\r\n 10011： ID为空\r\n\r\n五、实例代码：\r\n\r\n<script type="javascript/text">\r\n\r\n$.ajax({\r\n\r\n  url:''域名/index.php?m=zyaddr&c=zyaddr_api&a=del'',\r\n\r\n  data:{id:"1",\r\n     userid:"1",\r\n     name :"收件人",\r\n     phone:" 手机号码",\r\n     province :"省",\r\n     city :"市",\r\n     distrct :"区",\r\n     address :"详细地址",\r\n     default :"1",\r\n},\r\n\r\n  dataType:''json'',\r\n\r\n  type:''get'',\r\n\r\n  success:function(res){\r\n\r\n  { "status": "success", "code": 200, "message": "操作成功" }\r\n\r\n  },\r\n\r\n});\r\n\r\n</script>', 'zyaddr3'),
('设置默认地址', 'zyaddr 地址管理', 'zyaddr', 'localhost/zm/index.php?m=zyaddr&c=zyaddr_api&a=change', '域名/index.php?m=zyaddr&c=zyaddr_api&a=change', '一、应用模块：地址模块      配置来源：设置会员地址\r\n\r\n二、用途：用于用户地址\r\n\r\n三、提供参数：\r\n\r\n 1）请求参数说明：\r\n      id（ID)  default (默认 1 非默认 0)\r\n\r\n 2）返回格式： json\r\n\r\n 3）请求方式： http  get', '一、请求参数：\r\n\r\n\r\n\r\n 1）请求参数说明：\r\n\r\n      id（ID)  default (默认 1 非默认 0)\r\n\r\n 2）请求方式： http get\r\n\r\n\r\n二、返回信息 :\r\n\r\n  返回格式：{ "status": "success", "code": 200, "message": "操作成功" }\r\n\r\n\r\n三、返回字段解释：\r\n\r\n\r\n  status: 操作成功/操作失败\r\n\r\n  code: 操作状态\r\n\r\n  message: 提示信息\r\n\r\n四、状态信息说明：\r\n\r\n 200：操作成功\r\n\r\n 10001： ID为空\r\n\r\n 10002： 默认参数为空\r\n\r\n 10003： 设置失败\r\n\r\n\r\n五、实例代码：\r\n\r\n<script type="javascript/text">\r\n\r\n$.ajax({\r\n\r\n  url:''域名/index.php?m=zyaddr&c=zyaddr_api&a=change'',\r\n\r\n  data:{id:1,default:1},\r\n\r\n  dataType:''json'',\r\n\r\n  type:''get'',\r\n\r\n  success:function(res){\r\n\r\n   { "status": "success", "code": 200, "message": "操作成功" }\r\n\r\n  },\r\n\r\n});\r\n\r\n</script>', 'zyaddr5'),
('获取默认地址内容', 'zyaddr 地址管理', 'zyaddr', 'localhost/zm/index.php?m=zyaddr&c=zyaddr_api&a=getdefault', '域名/index.php?m=zyaddr&c=zyaddr_api&a=getdefault', '一、应用模块：地址模块      配置来源：设置会员地址\r\n\r\n二、用途：用于用户地址\r\n\r\n三、提供参数：\r\n\r\n 1）请求参数说明：\r\n     userid  用户ID\r\n\r\n 2）返回格式： json\r\n\r\n 3）请求方式： http  get', '一、请求参数：\r\n\r\n\r\n\r\n 1）请求参数说明：\r\n\r\n     userid  用户ID\r\n\r\n 2）请求方式： http get\r\n\r\n\r\n二、返回信息 :\r\n\r\n  返回格式：{\r\n    "status": "success",\r\n    "code": 200,\r\n    "message": "操作成功",\r\n    "data": {\r\n        "id": "7",\r\n        "userid": "22",\r\n        "name": "鹿晗",\r\n        "phone": "15728293911",\r\n        "province": "北京市",\r\n        "city": "北京市",\r\n        "district": "东城区",\r\n        "address": "市府大道3栋5门23号",\r\n        "default": "1"\r\n    }\r\n}\r\n\r\n\r\n三、返回字段解释：\r\n\r\n\r\n  status: 操作成功/操作失败\r\n\r\n  code: 操作状态\r\n\r\n  message: 提示信息\r\n\r\n四、状态信息说明：\r\n\r\n 200：操作成功\r\n\r\n 10001： 用户ID为空\r\n\r\n\r\n五、实例代码：\r\n\r\n<script type="javascript/text">\r\n\r\n$.ajax({\r\n\r\n  url:''域名/index.php?m=zyaddr&c=zyaddr_api&a=getdefault'',\r\n\r\n  data:{userid:1},\r\n\r\n  dataType:''json'',\r\n\r\n  type:''get'',\r\n\r\n  success:function(res){\r\n\r\n{\r\n    "status": "success",\r\n    "code": 200,\r\n    "message": "操作成功",\r\n    "data": {\r\n        "id": "7",\r\n        "userid": "22",\r\n        "name": "鹿晗",\r\n        "phone": "15728293911",\r\n        "province": "北京市",\r\n        "city": "北京市",\r\n        "district": "东城区",\r\n        "address": "市府大道3栋5门23号",\r\n        "default": "1"\r\n    }\r\n  },\r\n\r\n});\r\n\r\n</script>', 'zyaddr6');
